{% set name = "pyprojroot" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 109705bb790968704958efcfc5ccce85d8e3dafa054897cc81371fcbbf56cb10

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyprojroot

about:
  home: https://github.com/chendaniely/pyprojroot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Find project root paths and return relative project files

extra:
  recipe-maintainers:
    - achimgaedke
    - jamesmyatt
    - philip-khor
